### ISSUE TITLE
Refactor RegisterSchemasService to share logic with PerformanceService

### ISSUE THREAD

**Issue by granders** [confluentinc/ducktape#11]
Per Ewen's comment in PR #4 -

This code looks nearly the same as PerformanceService, which I refactored so it's 4 subclasses wouldn't need to reimplement this. Maybe we should refactor further so it's available more generally? Maybe called SynchronousWorkerService since the problem it's addressing is when the service's task is synchronous and so needs to be put on a background worker thread. It could just be included in the service.py file.

**Comment by ewencp** [comment]
This issue was moved to confluentinc/muckrake#8
