### ISSUE TITLE
add ignore or ok_to_fail annotation

### ISSUE THREAD

**Issue by granders** [confluentinc/ducktape#112]
When tests are failing repeatedly, we can temporarily mark with `@ok_to_fail` or `@ignore` to avoid excessive noise for those paying attention to the test runs.

`@ignore` temporarily disables a test or group of tests
Ignored tests are discovered, but not run. The test report(s) should include a summary of ignored tests.

**Comment by nehanarkhede** [comment]
Nice to see this :)

**Comment by granders** [comment]
:)

**Comment by granders** [comment]
fixed via https://github.com/confluentinc/ducktape/pull/115
