### ISSUE TITLE
Allow event driven mode where callback function can be scheduled

### ISSUE THREAD

**Issue by lindong28** [confluentinc/ducktape#118]
I am thinking if we can support event driver mode in Ducktape and allow developer to schedule callback function. This can be useful to write tests which start kafka server, run tools that monitor message loss rate, and execute arbitrary admin commands (e.g. topic creation, deletion, partition reassignment) repeatedly at regular interval.

Unlike existing system test that executes a given finite sequence of commands, this will enable test that runs in a real cluster for a long time until it is explicitly stopped.

**Comment by lindong28** [comment]
@granders @ewencp Do you think this is reasonable feature to include in Ducktape? If you agree I can propose its class structure and draft a patch for it.

**Comment by ewencp** [comment]
@lindong28 I'm not entirely sure what you have in mind. I think something like this could make sense if you can't guarantee an exact sequence of events in the tests and need to monitor for several possible events. So far we've tried to keep tests easy to understand by making tests as linear and straightforward as possible, but even some of our current tests don't work quite like that, e.g. we have to spawn background threads to monitor output to even be able to watch for certain events.

I think there's probably value in something like this, but I'm not sure what form it should take yet (or even if we need a generalized form of it yet). If we're going to add something like this, I think it'd be important to have an example test or two that we could use to better understand how the features should be designed.

**Comment by lindong28** [comment]
@ewencp Thanks for your comment. Here is an example test I have in mind -- we can start zookeeper, kafka server, and one producer and one consumer. producer produces message with increasing integer and consumer consumes message and reports metrics such as number of lost message, duplicated message, throughput and latency. In the meantime, we execute admin commands to bounce broker every 60 seconds, and re-assign partition of the topic at random interval between 30-90 seconds. We can run this test in a cluster for 1 week to validate kafka's functionality.

I think with the ability to schedule new function, we can write the test as follows

```
ZookeeperService.start()
KafkaService.start()
producer.start()
consumer.start()

scheduler.schedule(admin_rebounce_server, repeat=60)
scheduler.schedule(admin_rearrangement_partition_callback, time=now()+30)

def admin_rearrangement_partition_callback():
    admin_rearrangement_partition
    scheduler.schedule(admin_rearrangement_partition_callback, time=now()+rand.randInt(30, 60))

scheduler.run()
```

On the other hand, it is still possible, but unnecessarily complex for developer to write the same test with existing Ducktape API, because the developer needs to manually calculate the time to sleep until the next admin commands. The complexity adds up if there are more types of admin commands to be executed in the test. Does that make sense?

**Comment by ewencp** [comment]
@lindong28 Ah, I see. That makes sense a lot of sense -- seems especially useful for those repeating cases like bouncing/killing servers for fault tolerance tests. Something like this would definitely be useful and looks like it can just be a simple utility class (not even really ducktape specific). In fact, since that's the case, it might be worth checking if there are any good libraries that already have something similar or if we should provide our own in ducktape.

**Comment by lindong28** [comment]
@ewencp Yeah you are right. I forgot to search for existing libraries for this functionality. Look like Python does provide a class that implements a general purpose event scheduler. I will try that one first. Thanks for your comment.
