### ISSUE TITLE
Tweak strategy for selecting nodes when running benchmarks

### ISSUE THREAD

**Issue by ijuma** [confluentinc/ducktape#139]
Suppose we have 6 nodes and we run the same benchmark twice, but with different broker versions. The benchmark requires 3 nodes. What currently happens is that the first execution will use nodes 1, 2, 3 and the second execution will use nodes 4, 5, 6 even though they are running sequentially..

The fact that the benchmarks are being run in different machines can lead to differences in the results unrelated to the performance test itself (particularly true when running the benchmarks in environments like AWS).

It would be nice if it was possible to run both benchmarks in nodes 1, 2, 3.

I don't mind if this behaviour is optional or if we use it for all cases.

**Comment by ewencp** [comment]
@ijuma A couple of things. First, it's going to be difficult to be consistent when we have a parallel test runner. Not sure we even want to suggest we can guarantee it; or if we do, we might want to emphasize it will only be possible if you run tests serially to control for this.

Second, I actually would think the *opposite* should happen -- for performance tests, node assignment should be random. Especially when running in environments like AWS where you could see variations in performance for a variety of reasons. Perf tests should generally be run multiple times and you should look at the distribution (although admittedly tracking distributions over time may be difficult to understand so simplifying to, e.g., median or a few percentiles may be sufficient).

With that in mind, is consistent assignment what you want or just better support for perf tests in ducktape where you can repeat + summarize the set of executions (which might also require specialized test runner support).

**Comment by ijuma** [comment]
It's a good question.

First of all, running tests multiple times and tracking the distribution is definitely something we need (it's useful in a number of scenarios including the very common case of automatically checking for regressions).

The scenario I was thinking of is a bit specific, but important in my opinion. It's when you are comparing two versions of the code and you need to eliminate as many variables as possible. In this situation, consistent assignment is relatively cheap and does a reasonable job.

This came up while I was thinking why the results I was getting while testing KIP-31/32 were different than Becket's (who did not use ducktape). Another potential reason is that the performance tests may complete too quickly (https://issues.apache.org/jira/browse/KAFKA-3695).

**Comment by granders** [comment]
@ijuma @ewencp 
- For exploratory testing, it makes sense to want consistent ordering of machines to get apples to apples comparison - so that you have more confidence that you can attribute differences in results to the difference in version (or configuration etc) rather than the machines used.
-  For collecting stats perhaps many runs of the same test with randomization of the machines. But that's actually a different use-case I think
