### ISSUE TITLE
How to run the old tests?

### ISSUE THREAD

**Issue by szwed** [confluentinc/ducktape#141]
Hi,

Some time ago there was a directory called: _kafkatest_ containing "Collected 132 tests" but I cannot see it anymore..  is there any plan to restore the tests and integrate it with the current master?

Thanks,

**Comment by ewencp** [comment]
@szwed This repository started as an internal set of system tests developed at Confluent. We later converted `ducktape` to its own framework, open sourced and replaced the previous Kafka system tests, and use this framework for additional system tests of our platform.

The Kafka system tests are now part of the Kafka repository. You can find them (and instructions for running them) here: https://github.com/apache/kafka/tree/trunk/tests
