### ISSUE TITLE
Pysistence is incompatible with python 3

### ISSUE THREAD

**Issue by ivandasch** [confluentinc/ducktape#246]
`PDict` datastructure from `pysistence` is incompatible with python 3 pickle.
Simple test:
```
>>> import pysistence
>>> a = pysistence.make_dict({"test": "test"})
>>> pickle.loads(pickle.dumps(a))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ivandasch/.virtualenvs/ducktape-py37/lib/python3.7/site-packages/pysistence/persistent_dict.py", line 22, in not_implemented_method
    raise NotImplementedError('Cannot set values in a PDict')    
NotImplementedError: Cannot set values in a PDict
>>>
```
I suggest to replace this package with [pyrsistent](https://github.com/tobgu/pyrsistent/). It is MIT licensed, active developing alternative. PMap from it works both with python 2 and python 3, and is pickleable.

```
>>> import pyrsistent
>>> a = pyrsistent.pmap({"test": "test"})
>>> pickle.loads(pickle.dumps(a))
pmap({'test': 'test'})
>>> 
```

**Comment by ewencp** [comment]
We can look into it, but can you also include your python version? Tests against python3 still pass, so either we have a testing gap or maybe this became incompatible in py38.

Switching to a better maintained alternative is a good idea but a) probably a major version bump thing since it's a change in dependencies and b) we'd need to run through tests -- kafkatest is the default, Confluent also has a large suite of tests internally to test against.

**Comment by dotnwat** [comment]
I've hit this issue too when evaluating python3 support. One option that might be easier to merge without changes to the dependencies / major version bump is to instead of:

```
d = PDict()t
x = pickle.dumps(d)
<network>
y = pickle.loads(x)
```

use an intermediate form on either side of the network. something like:

```
d = PDict()t
d_out = dict(d) # not immutable form over the network
x = pickle.dumps(d_out)
<network>
y_in = pickle.loads(x)
y = PDict(y_in) # now make it immutable
```

**Comment by ivandasch** [comment]
@ewencp There is no test with --globals, this issue appears only when you are trying to use globals. I hits 3.6, 3.7 and 3.8 pythons. I will provide fix today within few hours. I am considering to add unit tests to cover this case and simply replace implementation of persistent collection (namely PMap)

Currently, we are running ducktape on python 3 flawlessly, but we are considering to use globals in near future and this issue will affect us. If you don't use globals, everything will work without any problem

**Comment by ivandasch** [comment]
@ewencp Actually pyrsistent depends on nothing, except for tests. But, actually, are persistent data structures REALLY needed?

**Comment by ivandasch** [comment]
@dotnwat Unfortunatelly, persistent dict is within session_context as a field. So we should add to SerDe additional logic. We can also make globals persistent in RunnerClient, but it seems a little bit crutchy.

@ewencp It will be nice if you write down your concerns about my suggestion.
As far as I understand, here they are:
1. Compatibility -- both of these libraries are drop in replacement of common datastructures. Nothing changes in code.
2. Dependecies -- pyrsistent depends on nothing. 
3. Compatibility across pythons -- I've checked both of them, using this simple tests, on py27, py36, py37, py38. Pysistence fails on thirds, pyrsistent works flawlessly (actually it have pickle unit test and tested across multiple versions).

So my point of view -- it is more safe to use pyrsistence -- minimal code change (just change imports and factory method name, replace 1 line in requirements.txt and setup.py), zero additional dependencies. 

Saving old library and introduce workarounds in code in perspective is far more risky.

**Comment by ivandasch** [comment]
Actually, there is another approach -- just reuse PDict class (it is simple class about 35 lines of code), but add this magic method
to it
```
    def __reduce__(self):
        # Pickling support
        return make_dict, (dict(self),)
```
And remove dependency to pysistence at all :) What do you think about this?

**Comment by nizhikov** [comment]
Hello, Ducktapers!

Let's completely eliminate `pysistence` dependency from ducktape?

As far as I can see the only usage of `pysistence` is the following:
```
        self._test_context = pysistence.make_dict(**{t.test_id: t for t in tests})
```
We just make sure that `_test_context` dict is immutable.

Looks like we have at least 2 good options:

1. Eliminate this line with the `self._test_context = **{t.test_id: t for t in tests}`. Because this dict not really read-only. Anyone can assign `self_test_context` variable with a copy of it.

2. Have our own implementation of read-only dict. This will be just 30 additional LOC.

What do you think?

**Comment by nizhikov** [comment]
Sorry, we have the second usage of `pysistence` in the `main.py`
Looks like this line can be replaced with the regular dict or our own immutable dict implementation, also.

```
    # Use pysistence to create the immutable dict
    user_globals = pysistence.make_dict(**user_globals)
```

**Comment by ivandasch** [comment]
@nizhikov @ewencp @dotnwat I decided to implement the latest suggesion in #248, just add PDict to ducktape codebase and fix it. I additionally tested it manually with --globals on our tests. Everything works as it should.
