### ISSUE TITLE
Removed support for python 3.6

### ISSUE THREAD

**Issue by ivandasch** [confluentinc/ducktape#269]
Recently discovered, that support for python 3.6 is removed. Checked locally -- all tests run flawlessly without any problem.

Our testing environment use 3.6, but we cannot use 0.8.2 version of ducktape from pip.

**Comment by stan-confluent** [comment]
@ivandasch gotcha, let me fix this today

**Comment by stan-confluent** [comment]
Version 0.8.3 has been uploaded to pypi

**Comment by stan-confluent** [comment]
ugh, I've mixed up the branches, 0.8.3 doesn't contain your fix. Let me fix it properly this time

**Comment by stan-confluent** [comment]
Ok, it should be good now, v0.8.4 is up there and should support py36. Please let me know if you run into any issues and sorry for the confusion!

**Comment by ivandasch** [comment]
@stan-confluent  Thanks a lot for your help. But we already decided to move to python 3.8, but for someone this will be valuable.

**Comment by stan-confluent** [comment]
@ivandasch no worries, please let us know if you run into any other issues.

**Comment by ewencp** [comment]
Closing since this should be fixed in 0.8.4
