### ISSUE TITLE
Documentation on readthedocs.io is outdated

### ISSUE THREAD

**Issue by vp-elitnet** [confluentinc/ducktape#286]
The [documentation site](http://ducktape-docs.readthedocs.io/) linked from the project README is out of sync with the content in project repo. readthedocs.io shows "v:latest" with no other options, however, the page title is "Ducktape 0.7.4 documentation". For example, the documentation on test suites is missing in [Run Tests](https://ducktape-docs.readthedocs.io/en/latest/run_tests.html) section, while test suites are actually documented in the [project repo](https://github.com/confluentinc/ducktape/blob/master/docs/run_tests.rst).

**Comment by andrewhsu** [comment]
I've been using https://ducktape.readthedocs.io/en/latest/ which seems up-to-date.

**Comment by vp-elitnet** [comment]
The "documentation site" link in issue description redirects to the URL posted by @andrewhsu. I do not see any change since the issue has been reported - the title is still outdated, test suite documentation is still missing. These are just a couple of indications of the documentation being outdated that I came across. I assume it simply needs to be regenerated (or the automatic job responsible for that fixed if there is one) and there's no point in compiling an exhaustive list of doc errors.

**Comment by vp-elitnet** [comment]
Thanks for pointing out the up-to-date doc link, @andrewhsu! I've proposed a change to the README to refer to this link instead of the outdated one.

**Comment by imcdo** [comment]
cc @stan-confluent does this need to be updated again?

**Comment by stan-confluent** [comment]
Yes, thank you, let me update it!

**Comment by stan-confluent** [comment]
- https://github.com/confluentinc/ducktape/pull/349
- https://github.com/confluentinc/ducktape/pull/350
- https://github.com/confluentinc/ducktape/pull/351
- https://github.com/confluentinc/ducktape/pull/352
- https://github.com/confluentinc/ducktape/pull/353
