### ISSUE TITLE
Support the most recent pythons in ducktape

### ISSUE THREAD

**Issue by ivandasch** [confluentinc/ducktape#398]
@confluentinc/devprod-apac-n-frameworks-eng is tagged for visibility

Currently, the most recent version that is ok with current ducktape is python 3.9

PR #397 fixes this issue. Could you please review it?

**Comment by premk92** [comment]
@ivandasch thanks for adding the support. I am reviewing the changes.

**Comment by nizhikov** [comment]
Hello @premk92 
Is there any chance to get this PR reviewed?
