### ISSUE TITLE
min_cluster_size error can be a bit nicer

### ISSUE THREAD

**Issue by gwenshap** [confluentinc/ducktape#62]
Currently we have:
There aren't enough available nodes to satisfy the resource
request. Your test has almost certainly incorrectly implemented its
min_cluster_size() method.

Will be nice to include:
* Expected cluster size
* Where is it actually configured (in case I want to fix my incorrect setting)
* Maybe even justification ("We need 3 brokers, 1 zk, 1 runner")
* Actual cluster size
* How did you get the actual size (in case there is a bug and you are miscounting)
* Output of Vagrant Status, so we will see who is right
* "Your test has almost certainly incorrectly implemented its
min_cluster_size() method" should be changed to "Either your test incorrectly implemented its
min_cluster_size() method or you did not start enough Vagrant workers for the test to execute."

Also, kittens and unicorns :)

**Comment by granders** [comment]
closed via #67
