### ISSUE TITLE
update html report to include test data

### ISSUE THREAD

**Issue by granders** [confluentinc/ducktape#70]
Some tests now return data (e.g. various performance tests)

This data is now available in Result objects, and should be visible on generated html reports

**Comment by ewencp** [comment]
Possibly worth doing in the same patch: include running time somewhere in this report so it's easy to see which tests are costly.

**Comment by ewencp** [comment]
Also should include links to the session.info and session.debug logs.

**Comment by edenhill** [comment]
See if the TestAction() can be used for this, they are integrated with the HTML reporter and also feature an .add_result() function for adding aux result information.
