### ISSUE TITLE
Difficult to discover bugs in cleanup code

### ISSUE THREAD

**Issue by ewencp** [confluentinc/ducktape#81]
When developing a test, I started noticing weird behavior and eventually tracked it down to the fact that my service had not been cleaning up properly. There were still instances of it running when I ran the test again and it caused the test to break (they were auto-registering Kafka topics when the test wasn't expecting them to).

It took me awhile to discover this because even though there was a log indicating that the stop method was failing, it was buried in the info/debug logs and at the WARNING level:

```
[WARNING - 2015-08-14 10:20:39,176 - service_registry - stop_all - lineno:37]: Error stopping service <CopycatStandaloneService: num_nodes: 1, allocated: True, nodes: ['worker3']>: pids() takes exactly 1 argument (2 given)
```

Any reason this is only at the WARNING level? I think the obvious thing to do is log it at the error level, make sure it gets logged to the console (not just in the log files that I'd have to look at separately).

**Comment by granders** [comment]
Error level makes sense, especially given that problems with cleanup is currently a common source of test instability
